
source .meta

@default-request = chat


### [request] chat
POST {{copilotAdapterHost}}/v1/chat/completions
Content-Type: application/json

{
    "model": "{{model}}",
    "messages": [
        {
            "role": "{{role}}",
            "content": "{{content}}"
        }
    ],
    "stream": {{stream}}
}
